name: Run end-to-end tests

on:
  workflow_dispatch:

jobs:
  cypress-e2e:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    container: cypress/browsers:latest

    steps:
      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        continue-on-error: true
        env:
          CYPRESS_baseUrl: https://trainee.tis.nhs.uk
          CYPRESS_password: ${{ secrets.E2E_TEST_PASS }}
          CYPRESS_username: ${{ secrets.E2E_TEST_USER }}
        with:
          browser: chrome

      - name: Merge test results into one
        run: npm run report:merge

      - name: Generate HTML report
        run: npm run report:generate

      - name: Create report artifact
        uses: actions/upload-artifact@v2
        with:
          name: cypress-reports
          path: cypress/reports

      - name: Create screenshot artifact
        uses: actions/upload-artifact@v2
        # No screenshots generated if tests pass.
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Create video artifact
        uses: actions/upload-artifact@v2
        # Test run video was always captured, so this action uses "always()" condition
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

  backup-artifacts:
    name: Backup build artifacts
    needs: cypress-e2e
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          path: build-artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Backup build artifacts
        run: |
          workflow=$(echo ${{ github.workflow }} | sed -e 's/\W/-/g' -e 's/\(.*\)/\L\1/')
          aws s3 sync build-artifacts s3://tis-build-artifacts/${{ github.event.repository.name }}/$workflow/${{ github.run_number }}
